### PR TITLE
New Feature: Optionally require an admin to approve the registration

### PR DESCRIPTION
**Pull request by theCalcaholic**
These commits add a new checkbox in the admin settings. If checked, any user will be disabled after completing the self-registration and a notification email will be sent to the admin.

The admin can thereafter enable the user in the users panel.

If you like to add the changes, feel free to do so.
I haven't added any localization though.

### CODE REVIEW

**Comment by theCalcaholic** [comment]
I just found out about the admin-approval branch. Sorry for not informing myself properly beforehand.

**Comment by pellaeon** [comment]
Yep, as for now it seems to be a good enough replacement though, since the admin-approval branch is a bit heavy work. If you still would like to work on this, fix the conflict and I will test and merge it.

Or I would also gladly answer questions with the `admin-approval` branch.

Thanks for your contribution!

**Comment by theCalcaholic** [comment]
@pellaeon I *mostly* resolved the conflict, but I'm stuck with reinjecting the config dependency into registercontroller.php. I've created an [issue where the problem is explained in depth](https://github.com/theCalcaholic/registration/issues/1).

Could you have a look into this? It should be easily resolvable for someone who is more experienced in using the nextcloud app framework.

**Comment by Neraste** [comment]
Hey there. I made a new PR using this one as model, plus some adjustments. I managed to avoid the problem of config dependency reinjection. It works fine.

**Comment by theCalcaholic** [comment]
@Neraste Awesome. Thanks for the work!

**Comment by Neraste** [comment]
You did most of the job, so thank you as well.

**Pull request closed without merging**
